apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-rest-api
  template:
    metadata:
      labels:
        app: my-rest-api
    spec:
      containers:
      - name: my-rest-api
        image: vikashdev/microservices-app:lts
        ports:
        - containerPort: 3000
